### ISSUE TITLE
Process gets stuck on send page.

### ISSUE THREAD

**Issue by geekthattweaks** [mctrivia/DigiSweep#12]
Ran into a bit of an issue getting DigiSweep to finish. I work through all of the pages but after I click next on the send page it just stays with the Sending window and the Digi is not tranferred. 

Not sure what further information would help with troubleshooting but happy to gather any information needed.

Many thanks!

**Comment by mctrivia** [comment]
This version has been deprecated for exactly this reason.  New version is available at DigiSweep.digiassetX.com 

Have not removed this version because the old android and copay inputs have not yet be transfered.  If using those then export wallet instead of send and use new version to move the private keys(value after , in each one of csv file)

**Comment by geekthattweaks** [comment]
Ok thank you for the information. I did not see any deprecated notices or pointers to new version so my bad.
